# Generated by Django 2.2.7 on 2019-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191112_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/books_pdf')),
            ],
        ),
    ]
