# Generated by Django 2.2.7 on 2019-11-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BPdf',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='uploads/books_pdf'),
        ),
    ]
